version: '3.9'
services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - db.env
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables (DDL)
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to hydrate tables (DML)
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/hydrate_tables.sql
